Add ./bin; add dot command; improve code
Was: no dot commands
Now: "./with . FOO [...]" will run ./bin/FOO [...]"

Rename functions to lead with double underscores to reduce
nameclashes when calling with.

diff --git a/with b/with
--- a/with
+++ b/with
@@ -1,32 +1,61 @@
 NAME=r20
+URL=https://github.com/bryanhann/${NAME}.git
 
 pushd $0/.. > /tmp/foo ; 
     export   RXX=$PWD 
+    export  VENV=$PWD/__VENV__
+    SCRIPT="import sys;print([p for p in sys.path if p.startswith('${VENV}')][0])"
+    FLAG=${VENV}/.flag_pip_upgraded
 popd > /tmp/foo
 
-export VENV=${RXX}/__VENV__
-PY="import sys;print([p for p in sys.path if p.startswith('${VENV}')][0])"
-FLAG=${VENV}/.flag_pip_upgraded
-SRC=https://github.com/bryanhann/r20.git
+function __usage {
+    echo
+    echo "usage:"
+    echo "    $0 python -m ${NAME}"
+    echo "    $0 [args]"
+    echo "    $0 . SUBCOMMAND [args]"
+    echo
+    echo "Runs in a virtual environment."
+    echo
+    echo subcommands:
+    for ii in $(ls -A ${RXX}/bin); do echo "    $0 . $ii [args]"; done
+    echo
+}
+ 
+function __remove   { rm -rf ${VENV}; }
+function __install  { python3 -m venv ${VENV}; }
+function __activate { . ${VENV}/bin/activate ; }
+function __upgrade  { pip install --upgrade pip; }
+function __clone    { __active && git clone $URL $(__dst); }
+function __warn     { echo "$0: WARNING: cannot import r20"; }
+function __dst      { echo $(__site)/${NAME}; }
+function __check    { python -m ${NAME} __exit__ 42 >/tmp/foo 2>/tmp/foo ; echo $?; }
+function __site     { echo $(python -c "$SCRIPT" 2> /tmp/foo); }
+function __active   { [ -z "$(__site)" ] && return 1 || return 0 ;}
 
-function src      { echo https://github.com/bryanhann/${NAME}; }
-function dst      { echo $(site)/${NAME}; }
-function site     { echo $(python -c "$PY" 2> /tmp/foo); }
-function active   { [ -z "$(site)" ] && return 1 || return 0 ;}
-function check    { python -m ${NAME} >/tmp/foo 2>/tmp/foo || echo FAIL; }
-function gosite   { PATH=${RXX}/bin:$PATH; pushd $(site); bash; }
-
-[ .$1 == .-v  ] && rm -rf $VENV
-[ .$1 == .-v  ] && shift
-[ -d ${VENV}  ] || python3 -m venv ${VENV}
-[ true        ] && source ${VENV}/bin/activate
-[ -f ${FLAG}  ] || pip install --upgrade pip
-[ -f ${FLAG}  ] || touch ${FLAG}
-[ ! -d $(dst) ] && active && git clone $(src) $(dst)
-[ -z $(check) ] || echo "$0: FAIL: cannot import r20"
-[ -z $(check) ] || exit
-
+if [ .$1 == .-v           ]; then __remove   ;shift;fi
+if [ ! -d ${VENV}         ]; then __install  ;fi
+if [ true                 ]; then __activate ;fi
+if [ ! -f ${FLAG}         ]; then __upgrade  ;touch ${FLAG};fi
+if [ ! -d $(__dst)        ]; then __clone    ;fi
+if [ ! .$(__check) == .42 ]; then __warn     ;fi
+if [ "$1" == "-s"         ]; then __site; exit; fi
+if [ "$1$2" == "."        ]; then __usage    ;exit; fi
+if [ "$1" == "."          ]; then shift    ;${RXX}/bin/$*;exit;fi
 $*
 
+ 
+ 
+ 
+ 
+ 
+ 
+ 
+ exit
+    exit
+elif [ -f ${RXX}/bin/$1 ]; 
+    then ${RXX}/bin/$* ;
+    else $* ;
+fi
 
 
